INSERT INTO `log_champion` (`id`, `name`, `image`) VALUES
(1, 'Morgana', 'Morgana.jpg'),
(2, 'Ahri', 'Ahri.jpg'),
(3, 'Akali', 'Akali.jpg'),
(4, 'Alistar', 'Alistar.jpg'),
(5, 'Amumu', 'Amumu.jpg'),
(6, 'Anivia', 'Anivia.jpg'),
(7, 'Annie', 'Annie.jpg'),
(8, 'Ashe', 'Ashe.jpg'),
(9, 'Blitzcrank', 'Blitzcrank.jpg'),
(10, 'Brand', 'Brand.jpg'),
(11, 'Caitlyn', 'Caitlyn.jpg'),
(12, 'Cassiopeia', 'Cassiopeia.jpg'),
(13, 'Cho Gath', 'ChoGath.jpg'),
(14, 'Corki', 'Corki.jpg'),
(15, 'Dr. Mundo', 'DrMundo.jpg'),
(16, 'Evelynn', 'Evelynn.jpg'),
(17, 'Ezreal', 'Ezreal.jpg'),
(18, 'Fiddlesticks', 'Fiddlesticks.jpg'),
(19, 'Fiora', 'Fiora.jpg'),
(20, 'Fizz', 'Fizz.jpg'),
(21, 'Galio', 'Galio.jpg'),
(22, 'Gangplank', 'Gangplank.jpg'),
(23, 'Garen', 'Garen.jpg'),
(24, 'Gragas', 'Gragas.jpg'),
(25, 'Graves', 'Graves.jpg'),
(26, 'Hecarim', 'Hecarim.jpg'),
(27, 'Heimerdinger', 'Heimerdinger.jpg'),
(28, 'Irelia', 'Irelia.jpg'),
(29, 'Janna', 'Janna.jpg'),
(30, 'Jarvan IV', 'JarvanIV.jpg'),
(31, 'Jax', 'Jax.jpg'),
(32, 'Karma', 'Karma.jpg'),
(33, 'Karthus', 'Karthus.jpg'),
(34, 'Kassadin', 'Kassadin.jpg'),
(35, 'Katarina', 'Katarina.jpg'),
(36, 'Kayle', 'Kayle.jpg'),
(37, 'Kennen', 'Kennen.jpg'),
(38, 'Kog''Maw', 'KogMaw.jpg'),
(39, 'LeBlanc', 'LeBlanc.jpg'),
(40, 'Lee Sin', 'LeeSin.jpg'),
(41, 'Leona', 'Leona.jpg'),
(42, 'Lulu', 'Lulu.jpg'),
(43, 'Lux', 'Lux.jpg'),
(44, 'Malphite', 'Malphite.jpg'),
(45, 'Malzahar', 'Malzahar.jpg'),
(46, 'Maokai', 'Maokai.jpg'),
(47, 'Master Yi', 'MasterYi.jpg'),
(48, 'Miss Fortune', 'MissFortune.jpg'),
(49, 'Mordekaiser', 'Mordekaiser.jpg'),
(50, 'Nasus', 'Nasus.jpg'),
(51, 'Nautilus', 'Nautilus.jpg'),
(52, 'Nidalee', 'Nidalee.jpg'),
(53, 'Nocturne', 'Nocturne.jpg'),
(54, 'Nunu', 'Nunu.jpg'),
(55, 'Olaf', 'Olaf.jpg'),
(56, 'Orianna', 'Orianna.jpg'),
(57, 'Pantheon', 'Pantheon.jpg'),
(58, 'Poppy', 'Poppy.jpg'),
(59, 'Rammus', 'Rammus.jpg'),
(60, 'Renekton', 'Renekton.jpg'),
(61, 'Riven', 'Riven.jpg'),
(62, 'Rumble', 'Rumble.jpg'),
(63, 'Ryze', 'Ryze.jpg'),
(64, 'Sejuani', 'Sejuani.jpg'),
(65, 'Shaco', 'Shaco.jpg'),
(66, 'Shen', 'Shen.jpg'),
(67, 'Shyvana', 'Shyvana.jpg'),
(68, 'Singed', 'Singed.jpg'),
(69, 'Sion', 'Sion.jpg'),
(70, 'Sivir', 'Sivir.jpg'),
(71, 'Skarner', 'Skarner.jpg'),
(72, 'Sona', 'Sona.jpg'),
(73, 'Soraka', 'Soraka.jpg'),
(74, 'Swain', 'Swain.jpg'),
(75, 'Talon', 'Talon.jpg'),
(76, 'Taric', 'Taric.jpg'),
(77, 'Teemo', 'Teemo.jpg'),
(78, 'Tristana', 'Tristana.jpg'),
(79, 'Trundle', 'Trundle.jpg'),
(80, 'Tryndamere', 'Tryndamere.jpg'),
(81, 'Twisted Fate', 'TwistedFate.jpg'),
(82, 'Twitch', 'Twitch.jpg'),
(83, 'Udyr', 'Udyr.jpg'),
(84, 'Urgot', 'Urgot.jpg'),
(85, 'Varus', 'Varus.jpg'),
(86, 'Vayne', 'Vayne.jpg'),
(87, 'Veigar', 'Veigar.jpg'),
(88, 'Viktor', 'Viktor.jpg'),
(89, 'Vladimir', 'Vladimir.jpg'),
(90, 'Volibear', 'Volibear.jpg'),
(91, 'Warwick', 'Warwick.jpg'),
(92, 'Wukong', 'Wukong.jpg'),
(93, 'Xerath', 'Xerath.jpg'),
(94, 'Xin Zhao', 'XinZhao.jpg'),
(95, 'Yorick', 'Yorick.jpg'),
(96, 'Ziggs', 'Ziggs.jpg'),
(97, 'Zilean', 'Zilean.jpg'),
(98, 'Darius', 'Darius.jpg');

